name: mapshop_tanzania
description: Map-Based E-Commerce Platform for Smart Local Shopping and Delivery
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  intl: ^0.18.1
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  graphql_flutter: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/