# Generated by Django 5.0.3 on 2026-04-11 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+255XXXXXXXXX'", regex='^\\+255\\d{9}$')]),
        ),
    ]
